### ISSUE TITLE
I think bestbuy store it not currently working with the script 

### ISSUE THREAD

**Issue by aRealBanana** [PrinceS25/StockAlertBot#30]
I tried to make changes to make sure if it is an error from my side but I could not find where is the issue.

**Comment by PrinceS25** [comment]
Could you please elaborate more? What kind of error is it? Is there a log? If so, could you please attach it?

**Comment by aRealBanana** [comment]
### So basically I tried this link for testing 
https://www.bestbuy.com/site/philips-hue-play-white-color-ambiance-smart-led-bar-light-2-pack-multicolor/6298635.p?skuId=6298635

### it shows this in the error logs:
 
TypeError: Cannot read property 'childNodes' of undefined
    at Timeout.bestbuy [as _onTimeout] (file:///C:/Users/alsaf/Desktop/coding/StockAlertBot-proxies/stores/bestbuy.js:55:67)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

and sometimes when I connect to a US VPN it does not show anything.

**Comment by aRealBanana** [comment]
I think this page is the problem 
![image](https://user-images.githubusercontent.com/47155982/105611955-b156d680-5dc9-11eb-9f70-bf459cc621dd.png)

But still when I connect to a US VPN there is no output, it think there is a problem with the code of bestbuy store somewhere.

**Comment by PrinceS25** [comment]
Yeah. If it redirects you to a different page, it's going to be a problem. What country are you in? Can you provide a HTML file of that page?

**Comment by aRealBanana** [comment]
Am currently in Kuwait
This is the page: https://www.bestbuy.com/site/philips-hue-play-white-color-ambiance-smart-led-bar-light-2-pack-multicolor/6298635.p?skuId=6298635

I can open it without any problem and it shows add to cart and everything. 
could you please test if bestbuy is even working in your side to make sure the problem is on my side.

**Comment by Jeisonx** [comment]
Is definitely working on my end
<img width="300" alt="Screen Shot 2021-01-24 at 1 24 09 PM" src="https://user-images.githubusercontent.com/22186712/105639796-31238600-5e48-11eb-8322-263973bb3767.png">

 as @PrinceS25 said if when you first access best buy you get redirected to "Hello choose your language" page because you're located in a different country that page has a different HTML and the bot will not work properly. My guess as a possible fix could be when best buy gets proxy support added you can use a proxy based on USA to avoid being redirected to "Hello choose your language" page or if @PrinceS25  is able to get it work.

**Comment by aRealBanana** [comment]
Oh, then I will do try to figure it out from my end, thanks!

**Comment by PrinceS25** [comment]
@aRealBanana May I ask why you're trying to use Best Buy if you're in Kuwait? Do they ship internationally? You could try using a VPN to switch a US, Canada or Mexico IP.

**Comment by aRealBanana** [comment]
Im trying to get my 3080 for retail price because in here its almost double its price, I can ship it to a friend in the US and then he ships it to me which will be so worth it in my case.

**Comment by PrinceS25** [comment]
Then unfortunately, the only way is for you to get a US IP using a VPN.
