### ISSUE TITLE
Amazon.de

### ISSUE THREAD

**Issue by backslash-f** [PrinceS25/StockAlertBot#45]
Doesn't seem to work with `Amazon.de`

For example, the following URL (product in Stock):
```
https://www.amazon.de/dp/B08G4SR6C8
```

Gives me a `not in stock` message:
```
1:51:17 PM: "LEGO 42120 Technic Luftkissenboot f&uuml;r Rettungseins&auml;tze, 2-in-1 Modell, Bauset f&uuml;r Jungen und M&auml;dchen, Spielzeug ab 8 Jahren" not in stock at Amazon. Will keep retrying in background every 10 seconds
```

Should it work?

**Comment by PrinceS25** [comment]
Sorry for the late response, @backslash-f .
Is it in stock? Could you provide a screenshot of the page if it is?

**Comment by backslash-f** [comment]
No worries.

Yeah, it's in stock. I think it should work based on what you wrote, but not sure:

![image](https://user-images.githubusercontent.com/664951/110113672-b8eba100-7db3-11eb-864f-0a4a422e4c11.jpeg)

![image](https://user-images.githubusercontent.com/664951/110113697-c143dc00-7db3-11eb-9e81-d1b9a5946ca4.jpeg)

I'm actually interested on the PS5, but I was testing other products to check if the notification would land.

¯\_(ツ)_/¯

**Comment by PrinceS25** [comment]
Thanks for the update. I used VPN to go Germany's Amazon and yeah you were right. It is in stock. It seems like Amazon's merchant ID is different for that part of the world so it shows up as out of stock. To fix it, you can delete this line: https://github.com/PrinceS25/StockAlertBot/blob/13abdd256df876171eebd5ba2b19c8095bec62e0/stores/amazon.js#L53 and then change the following line to `res = await axios.get(url, options)`.

Unfortunately, I don't think I wanna make this change officially since most of the users are in the US and they rather not see other sellers. I was unable to find Amazon seller ID for Germany but if you come across it, let me know and I can put it in officially.

**Comment by backslash-f** [comment]
Gotcha. I'll try that. You could provide a field in the UI so international users could customize the `URL`. Just an idea, maybe it's not worth it (small international user base). Anyway, thanks for taking a look. Tschüss!

**Comment by PrinceS25** [comment]
Thanks for the suggestion. I thought about doing something similar but in reality, how many people are going to know about Amazon's seller ID if I can't find it myself. I would rather have it so it automatically applies the seller ID based on the domain, i.e., `.de`, `.com`, etc.

Good to hear it worked for you. Let me know if there's any more issues.
Please share and consider donating if my project helps you out so I can devote more time to this!

**Comment by Prince25** [comment]
@backslash-f Just to let you know, I've added the ability to change Amazon Regions or use particular merchants in 2006dca. So it should now work with non-US regions without any editing.
