### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by fo0b** [PrinceS25/StockAlertBot#5]
I installed the new version of the stock checker and after a while I get these two errors. Best-buy and Newegg are the only two stores I have products being checked. I have no knowledge of coding so I don't know whats going on, I've left the logs, though.

[logBestBuy.log](https://github.com/PrinceS25/StockAlertBot/files/5726699/logBestBuy.log)
[logNewegg.log](https://github.com/PrinceS25/StockAlertBot/files/5726700/logNewegg.log)

**Comment by PrinceS25** [comment]
This might be related to the product(s) you're trying to track. Could share the URLs you're using so I can attempt to reproduce the error?

**Comment by fo0b** [comment]
I have a ton, and I mean a TON of products I'm tracking, so I just copied the links from main.js and put them in a .txt file.

[links.txt](https://github.com/PrinceS25/StockAlertBot/files/5740716/links.txt)

**Comment by PrinceS25** [comment]
Does it stop and exit the program when the error occurs? If not, worry not because the program is still running in the background. Sometimes fetching the websites comes up with nothing so **only** for that try, the inventory check fails. If it is doing this for every single try, then it's a bigger issue and I'll need to fix it ASAP.

**Comment by fo0b** [comment]
No, the program stays open. I've only seen about two errors per website when I've run it. I'm glad to know that when I've been running it I haven't been missing out on stock changes.

**Comment by PrinceS25** [comment]
Glad to help. I should probably make it clear though.
